"""常量定义"""
from .keywords import (
    NEGATIVE_KEYWORDS,
    POSITIVE_KEYWORDS,
    FAKE_REVIEW_PATTERNS,
    SENTIMENT_THRESHOLDS
)

__all__ = [
    'NEGATIVE_KEYWORDS',
    'POSITIVE_KEYWORDS',
    'FAKE_REVIEW_PATTERNS',
    'SENTIMENT_THRESHOLDS'
]
